### PR TITLE
feat: application package loading for local file handling

### PR DESCRIPTION
**Pull request by dbrasseur-aneo**
Refactored application package loading to handle both zip and local folder

### CODE REVIEW

**Comment by dbrasseur-aneo** [comment]
> After giving more thoughts on that, I really dislike the lock approach. I think you should do with moves. I've checked, and moves are actually atomic not only on Linux, but also on Windows with NTFS, even though C# makes no guarantee about it. I think the wait free approach with moves is simpler and cleaner.

Issue still is with the extracted zip folder. Should I do it with a symlink approach ?

**Comment by lemaitre-aneo** [comment]
> > After giving more thoughts on that, I really dislike the lock approach. I think you should do with moves. I've checked, and moves are actually atomic not only on Linux, but also on Windows with NTFS, even though C# makes no guarantee about it. I think the wait free approach with moves is simpler and cleaner.
> 
> Issue still is with the extracted zip folder. Should I do it with a symlink approach ?

Yes, I would go with moving a symlink

**Comment by yanisallouch** [comment]
Howdy @dbrasseur-aneo, I took a look at this repo to grasp it and went through your community guidelines to join in later. I'm not sure if this counts as a breaking change according to [Conventional Commits v1.0](https://www.conventionalcommits.org/en/v1.0.0/). I'm asking because if it does, your commit message needs a `!`, as stated.

**Comment by dbrasseur-aneo** [comment]
> Howdy @dbrasseur-aneo, I took a look at this repo to grasp it and went through your community guidelines to join in later. I'm not sure if this counts as a breaking change according to [Conventional Commits v1.0](https://www.conventionalcommits.org/en/v1.0.0/). I'm asking because if it does, your commit message needs a `!`, as stated.

Hi, this change actually has mostly internal implications, and only adds ways to load the Assemblies, as such qualifying it as a "feat" is fair.

**Comment by aneojgurhem** [comment]
If it"s only internal, it should be `refactor:`

**Comment by dbrasseur-aneo** [comment]
> If it"s only internal, it should be `refactor:`

It's internal in nature for existing behavior (loading from zip), but it adds more feature (loading from a given directory instead for example)

**Comment by aneojgurhem** [comment]
So i'd not put refactor in the title, i'ts just feat

**Review by lemaitre-aneo — APPROVED** [review]

**Pull request merged**
